import { ArrowDownToLine, CircleHelp, LoaderCircle, Settings2, ShieldAlert, ShieldCheck, SlidersHorizontal, X } from 'lucide-react';
import type { Profile } from '../types';
import { commaList, initials } from '../helpers';
import { PageHeader } from './SharedUi';

export function SettingsPage(props: {
    profile: Profile | null; user: { name?: string; email?: string }; onEditProfile: () => void; onExport: () => void; onDelete: () => void;
    busyAction: string; exportStatus: string; deleteStatus: string;
}) {
    return <>
        <PageHeader kicker="YOUR ACCOUNT, YOUR CALL" title="Settings" description="Review your artist boundaries, export your information, or clear your NOTE workspace." />
        <div className="settings-grid">
            <section className="panel settings-panel"><div className="settings-title"><div className="settings-card-icon coral-icon"><Settings2 size={18} /></div><div><div className="panel-kicker">ARTIST PROFILE</div><h2>Your contact and territory boundaries</h2></div></div><div className="settings-profile"><div className="settings-avatar">{initials(props.profile?.artistName || props.user.name || props.user.email || 'N')}</div><div><strong>{props.profile?.artistName || 'Profile not set up'}</strong><span>{props.profile?.genre || 'Add genre and territory preferences'}</span></div></div><div className="settings-facts"><div><span>Home territory</span><strong>{props.profile?.homeTerritory || 'Not set'}</strong></div><div><span>Languages</span><strong>{commaList(props.profile?.languages) || 'Not set'}</strong></div><div><span>Campaign territories</span><strong>{props.profile?.territories.length ?? 0} selected</strong></div><div><span>Excluded contexts</span><strong>{props.profile?.prohibitedContexts || 'None recorded'}</strong></div></div><button className="button button-outline" type="button" onClick={props.onEditProfile}><SlidersHorizontal size={15} /> Edit artist profile</button></section>
            <section className="panel settings-panel"><div className="settings-title"><div className="settings-card-icon sage-icon"><ArrowDownToLine size={18} /></div><div><div className="panel-kicker">PORTABILITY</div><h2>Keep a copy of your records</h2></div></div><p className="settings-description">Export your profile, Song Passports, campaigns, opportunity records, activity, and income ledger as a JSON file.</p><div className="settings-security-note"><ShieldCheck size={15} /><span>The export is assembled from your private workspace, including paginated records.</span></div><button className="button button-dark" type="button" onClick={props.onExport} disabled={props.busyAction === 'export'}>{props.busyAction === 'export' ? <LoaderCircle className="spin" size={15} /> : <ArrowDownToLine size={15} />} Download my data</button>{props.exportStatus && <p className="progress-copy">{props.exportStatus}</p>}</section>
            <section className="panel settings-panel settings-danger"><div className="settings-title"><div className="settings-card-icon danger-icon"><ShieldAlert size={18} /></div><div><div className="panel-kicker">DELETE YOUR WORKSPACE</div><h2>Remove NOTE data</h2></div></div><p className="settings-description">Permanently delete your NOTE profile, releases, campaigns, opportunities, activity, and income records. The sign-in account remains active; this does not delete your external music service accounts or source statements.</p><div className="settings-security-note"><CircleHelp size={15} /><span>Export first if you may need a copy. Deletion proceeds one bounded database page at a time.</span></div><button className="button button-danger" type="button" onClick={props.onDelete} disabled={props.busyAction === 'delete-data'}>{props.busyAction === 'delete-data' ? <LoaderCircle size={15} className="spin" /> : <X size={15} />} Delete all NOTE data</button>{props.deleteStatus && <p className="progress-copy">{props.deleteStatus}</p>}</section>
        </div>
        <section className="panel privacy-panel"><div className="privacy-heading"><ShieldCheck size={18} /><div><div className="panel-kicker">WHAT NOTE DOES TODAY</div><h2>Data and provider transparency</h2></div></div><div className="privacy-columns"><div><strong>Connected to NOTE</strong><p>Secure sign-in, your private artist workspace, saved records, and the CSV statement lines you choose to import.</p></div><div><strong>Not connected</strong><p>DSPs, distributors, PROs/CMOs, advertisers, banks, payment processors, email, playlist platforms, or promotion outlets.</p></div><div><strong>External actions</strong><p>NOTE does not send outreach, upload music, buy ads, purchase placements, or spend money on your behalf.</p></div><div><strong>Statements</strong><p>Imported figures are labelled as artist-provided statements. A number in NOTE is not proof that a payer owes it.</p></div></div><p className="privacy-account">Signed in as {props.user.email || props.user.name || 'your account'}. NOTE’s legal terms and privacy materials are not finalized; use only information needed for this private preview.</p></section>
    </>;
}
